name: Export PLIST

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**'
      - '!sql/**.sql'
      - '!scripts/export**'

jobs:
  export_plist:
    name: PLIST
    if: ${{ contains(github.event.pull_request.labels.*.name, 'automated') }}

    runs-on: macos-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Export Script
        shell: bash
        run: |
          [ -d plist ] || mkdir plist
          sh ./scripts/export_plist.sh

      - name: Upload PLIST Exports
        uses: actions/upload-artifact@v2
        with:
          name: plist
          path: plist

  commit_plist:
    name: COMMIT_PLIST
    if: ${{ contains(github.event.pull_request.labels.*.name, 'automated') }}
    needs: export_plist
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ["7.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download PLIST Export
        uses: actions/download-artifact@v2
        with:
          name: plist
          path: plist

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update exported PLIST Files
          commit_user_name: dr5hn
          commit_user_email: gadadarshan@gmail.com
          commit_author: Darshan Gada <gadadarshan@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
